# Generated by Django 4.1.3 on 2022-11-26 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date_added'], 'verbose_name': 'categorie', 'verbose_name_plural': 'categories'},
        ),
    ]
