# Generated by Django 4.1.3 on 2022-11-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date_added'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
